language: java
os:
  - linux
env:
  - SPRING_PROFILES_ACTIVE=ci
install: true
jdk:
  - openjdk8
services:
  - mysql
before_script:
  - "mv tweet_streamer/example.properties tweet_streamer/gradle.properties"
script:
  - "./gradlew build -x test"
